### ISSUE TITLE
das repo hat einen irreführenden namen

### ISSUE THREAD

**Issue by neingeist** [entropia/gpn-guidlines#4]
"gpnpublic"? sollte imho guidelines oder coc o.ä. heissen.

**Comment by loelkes** [comment]
Ich habe gpn-guidlines draus gemacht. Danke!

**Comment by neingeist** [comment]
jetzt ist ein rechtschreibfehler drin :) guidelines mit e!

**Comment by loelkes** [comment]
Danke m)
